# Generated by Django 5.2 on 2025-04-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_user',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
    ]
